language: python
dist: xenial
python:
  - "3.7"
env:
  - FLASK=1.1.2
install:
  - pip install -q Flask==$FLASK
  - pip install -q -r dev_requirements.txt
  - pip install -q -e .
script: python3 main.py
